//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ventasservice.org/", ConfigurationName="Service.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/GetArticulos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ECommerce.Service.ArticuloDTO[] GetArticulos(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ECommerce.Service.ClienteDTO Login(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/Filtrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ECommerce.Service.ArticuloDTO[] Filtrar(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/Registro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ECommerce.Service.ClienteDTO Registro(string nombre, string direccion, string telefono, string email, string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/getArticuloDTO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ECommerce.Service.ArticuloDTO getArticuloDTO(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/traerDatosUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ECommerce.Service.ClienteDTO[] traerDatosUsuario(int usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/actualizarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarCliente(ECommerce.Service.ClienteDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/nuevaVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void nuevaVenta(int idcliente, ECommerce.Service.ArticuloDTO[] articuloscomprados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/verMisCompras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet verMisCompras(int idcliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ventasservice.org/actualizarStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarStock(ECommerce.Service.ArticuloDTO articulo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventasservice.org/")]
    public partial class ArticuloDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private decimal precioVentaField;
        
        private decimal precioCompraField;
        
        private int stockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal PrecioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                this.precioVentaField = value;
                this.RaisePropertyChanged("PrecioVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal PrecioCompra {
            get {
                return this.precioCompraField;
            }
            set {
                this.precioCompraField = value;
                this.RaisePropertyChanged("PrecioCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("Stock");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ventasservice.org/")]
    public partial class ClienteDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private string emailField;
        
        private string usuarioField;
        
        private string contraseñaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("Contraseña");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ECommerce.Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ECommerce.Service.ServiceSoap>, ECommerce.Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public ECommerce.Service.ArticuloDTO[] GetArticulos(string filtro) {
            return base.Channel.GetArticulos(filtro);
        }
        
        public ECommerce.Service.ClienteDTO Login(string usuario, string contraseña) {
            return base.Channel.Login(usuario, contraseña);
        }
        
        public ECommerce.Service.ArticuloDTO[] Filtrar(string filtro) {
            return base.Channel.Filtrar(filtro);
        }
        
        public ECommerce.Service.ClienteDTO Registro(string nombre, string direccion, string telefono, string email, string usuario, string contrasena) {
            return base.Channel.Registro(nombre, direccion, telefono, email, usuario, contrasena);
        }
        
        public ECommerce.Service.ArticuloDTO getArticuloDTO(int id) {
            return base.Channel.getArticuloDTO(id);
        }
        
        public ECommerce.Service.ClienteDTO[] traerDatosUsuario(int usuario) {
            return base.Channel.traerDatosUsuario(usuario);
        }
        
        public void actualizarCliente(ECommerce.Service.ClienteDTO cliente) {
            base.Channel.actualizarCliente(cliente);
        }
        
        public void nuevaVenta(int idcliente, ECommerce.Service.ArticuloDTO[] articuloscomprados) {
            base.Channel.nuevaVenta(idcliente, articuloscomprados);
        }
        
        public System.Data.DataSet verMisCompras(int idcliente) {
            return base.Channel.verMisCompras(idcliente);
        }
        
        public void actualizarStock(ECommerce.Service.ArticuloDTO articulo) {
            base.Channel.actualizarStock(articulo);
        }
    }
}
